name: mi primer robot
on:
  push:
    branches: [feature]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - name: saludo
        run: echo "hola mundo!"